export const movies = [
  {
    director: 'Denis Villeneuve',
    directorImage: '/directors/denis-villeneuve.jpg',
    id: '1',
    image: '/movies/arrival.jpg',
    name: 'Arrival',
  },
  {
    director: 'Rian Johnson',
    directorImage: '/directors/rian-johnson.jpg',
    id: '2',
    image: '/movies/knives-out.jpg',
    name: 'Knives Out',
  },
  {
    director: 'Christopher Nolan',
    directorImage: '/directors/christopher-nolan.jpg',
    id: '3',
    image: '/movies/memento.jpg',
    name: 'Memento',
  },
  {
    director: 'Edgar Wright',
    directorImage: '/directors/edgar-wright.jpg',
    id: '4',
    image: '/movies/baby-driver.jpg',
    name: 'Baby Driver',
  },
  {
    director: 'Greta Gerwig',
    directorImage: '/directors/greta-gerwig.jpg',
    id: '5',
    image: '/movies/lady-bird.jpg',
    name: 'Lady Bird',
  },
  {
    director: 'Wes Anderson',
    directorImage: '/directors/wes-anderson.jpg',
    id: '6',
    image: '/movies/grand-budapest-hotel.jpg',
    name: 'The Grand Budapest Hotel',
  },
  {
    director: 'Kenneth Lonergan',
    directorImage: '/directors/kenneth-lonergan.jpg',
    id: '7',
    image: '/movies/manchester-by-the-sea.jpg',
    name: 'Manchester by the Sea',
  },
  {
    director: 'Damien Chazelle',
    directorImage: '/directors/damien-chazelle.jpg',
    id: '8',
    image: '/movies/whiplash.jpg',
    name: 'Whiplash',
  },
  {
    director: 'Martin McDonagh',
    directorImage: '/directors/martin-mcdonagh.jpg',
    id: '9',
    image: '/movies/three-billboards-outside-ebbing-missouri.jpg',
    name: 'Three Billboards Outside Ebbing, Missouri',
  },
];
