import parseISO from 'date-fns/parseISO';

export const movies = [
  {
    director: 'Denis Villeneuve',
    directorImage: '/directors/denis-villeneuve.jpg',
    id: '1',
    image: '/movies/arrival.jpg',
    name: 'Arrival',
    releaseDate: parseISO('2016-09-01T00:00:00.000').getTime(),
    tags: ['Drama', 'Sci-Fi', 'Best Achievement in Sound Editing'],
  },
  {
    director: 'Rian Johnson',
    directorImage: '/directors/rian-johnson.jpg',
    id: '2',
    image: '/movies/knives-out.jpg',
    name: 'Knives Out',
    releaseDate: parseISO('2019-09-07T00:00:00.000').getTime(),
    tags: ['Comedy', 'Crime', 'Drama'],
  },
  {
    director: 'Christopher Nolan',
    directorImage: '/directors/christopher-nolan.jpg',
    id: '3',
    image: '/movies/memento.jpg',
    name: 'Memento',
    releaseDate: parseISO('2020-09-05T00:00:00.000').getTime(),
    tags: ['Mistery', 'Thriller'],
  },
  {
    director: 'Edgar Wright',
    directorImage: '/directors/edgar-wright.jpg',
    id: '4',
    image: '/movies/baby-driver.jpg',
    name: 'Baby Driver',
    releaseDate: parseISO('2017-03-11T00:00:00.000').getTime(),
    tags: ['Action', 'Crime', 'Drama'],
  },
  {
    director: 'Greta Gerwig',
    directorImage: '/directors/greta-gerwig.jpg',
    id: '5',
    image: '/movies/lady-bird.jpg',
    name: 'Lady Bird',
    releaseDate: parseISO('2017-09-01T00:00:00.000').getTime(),
    tags: ['Comedy', 'Drama'],
  },
  {
    director: 'Wes Anderson',
    directorImage: '/directors/wes-anderson.jpg',
    id: '6',
    image: '/movies/grand-budapest-hotel.jpg',
    name: 'The Grand Budapest Hotel',
    releaseDate: parseISO('2014-02-06T00:00:00.000').getTime(),
    tags: [
      'Adventure',
      'Comedy',
      'Crime',
      'Best Achievement in Costume Design',
      'Best Achievement in Makeup and Hairstyling',
      'Best Achievement in Music Written for Motion Pictures, Original Score',
      'Best Achievement in Production Design',
    ],
  },
  {
    director: 'Kenneth Lonergan',
    directorImage: '/directors/kenneth-lonergan.jpg',
    id: '7',
    image: '/movies/manchester-by-the-sea.jpg',
    name: 'Manchester by the Sea',
    releaseDate: parseISO('2016-01-23T00:00:00.000').getTime(),
    tags: [
      'Drama',
      'Best Performance by an Actor in a Leading Role',
      'Best Original Screenplay',
    ],
  },
  {
    director: 'Damien Chazelle',
    directorImage: '/directors/damien-chazelle.jpg',
    id: '8',
    image: '/movies/whiplash.jpg',
    name: 'Whiplash',
    releaseDate: parseISO('2014-01-16T00:00:00.000').getTime(),
    tags: [
      'Drama',
      'Music',
      'Best Performance by an Actor in a Supporting Role',
      'Best Achievement in Film Editing',
      'Best Achievement in Sound Mixing',
    ],
  },
  {
    director: 'Martin McDonagh',
    directorImage: '/directors/martin-mcdonagh.jpg',
    id: '9',
    image: '/movies/three-billboards-outside-ebbing-missouri.jpg',
    name: 'Three Billboards Outside Ebbing, Missouri',
    releaseDate: parseISO('2017-09-04T00:00:00.000').getTime(),
    tags: [
      'Comedy',
      'Crime',
      'Drama',
      'Best Performance by an Actress in a Leading Role',
      'Best Performance by an Actor in a Supporting Role',
    ],
  },
];
